### PR TITLE
Change StatsBlock component to typescript

### LINKED ISSUE #185: Convert StatsBlock component to TypeScript

### PR DESCRIPTION
**Pull request by ivanleeswe**
Change the StatsBlock js file to tsx.

### CODE REVIEW

**Review by richardxia — APPROVED** [review]
Awesome, thanks for working on this!

**Review by jessica-px — APPROVED** [review]
LGTM

**Review by candywang — APPROVED** [review]
LGTM!

**Review by davidagustin — APPROVED** [review]
LGTM

**Pull request merged**
