### PR TITLE
Upgrade to Gatsby 4 and Node.js 16

### PR DESCRIPTION
**Pull request by richardxia**
Refs #365, though doesn't get us all the way just yet.

This upgrade is partially motivated by the fact that you can't get the local development environment running on an Apple Silicon MacBook, due to dependencies that are too old and don't support the Arm CPUs. As described in #365, it's a bit too much to try to upgrade everything at once, so this is an incremental step that bumps Gatsby from v3 to v4 and Node.js from v14 to v16. Doing so required bumping a significant other number of dependencies, which is why I wanted to do this as an incremental step.

I have more details about specific workarounds in my individual commit messages, so please look at them if you're curious.

One thing that I will point out is that we are now getting a lot of warning messages. It doesn't seem to impact the behavior of the site, but most of them are things that we may want to fix before further upgrading packages, since a lot of them are deprecation warnings. I don't want to do them right now, though, since it was already a lot of work to get to this point.

To test this locally, please make sure you switch to Node 16 and then rerun the normal site setup (see the [README](https://github.com/ShelterTechSF/sheltertech.org/blob/61048d9753052a90cfada3adf8b654928106dd03/docs/getting-started.md)). If you use nvm (the Node version manager), you can automatically switch to the right version of Node.js by running `nvm use` in the repo, since I updated the `.nvmrc` file in this PR.

### CODE REVIEW

**Comment by schroerbrian** [comment]
I got stuck on installing the `node-sass` package. I tried a number of things, including installing Python via Home Brew and installing the latest node-gyp globally. When I remove the `node-sass` from the package.json, I'm able to run `npm i` successfully. 

I'm running Monterey version 12.5.1. My machine is using the Apple M1 Pro chip.

**Comment by richardxia** [comment]
> I got stuck on installing the `node-sass` package. I tried a number of things, including installing Python via Home Brew and installing the latest node-gyp globally. When I remove the `node-sass` from the package.json, I'm able to run `npm i` successfully.
> 
> I'm running Monterey version 12.5.1. My machine is using the Apple M1 Pro chip.

Thanks for trying this out! Which versions of `node` and `npm` do you have installed? I've got an M2 MBP running macOS Ventura 13.5, and this branch seems to work for me.

You might need to wipe your `node_modules` directory, since there may be leftover stuff from older package versions or Node.js versions.

In any case, I might just merge this PR in as is without removing `node-sass` as an explicit dependency, since it's no longer supported and should be replaced with the new `sass` package anyway. I think upgrading more of our packages will hopefully alleviate whichever issue you're hitting now, and it might not be worth fine tuning it until we get mostly caught up with the latest versions.

**Comment by schroerbrian** [comment]
> > I got stuck on installing the `node-sass` package. I tried a number of things, including installing Python via Home Brew and installing the latest node-gyp globally. When I remove the `node-sass` from the package.json, I'm able to run `npm i` successfully.
> > I'm running Monterey version 12.5.1. My machine is using the Apple M1 Pro chip.
> 
> Thanks for trying this out! Which versions of `node` and `npm` do you have installed? I've got an M2 MBP running macOS Ventura 13.5, and this branch seems to work for me.
> 
> You might need to wipe your `node_modules` directory, since there may be leftover stuff from older package versions or Node.js versions.
> 
> In any case, I might just merge this PR in as is without removing `node-sass` as an explicit dependency, since it's no longer supported and should be replaced with the new `sass` package anyway. I think upgrading more of our packages will hopefully alleviate whichever issue you're hitting now, and it might not be worth fine tuning it until we get mostly caught up with the latest versions.

Go for it! Let me know if you want me to check it out again. I'm running the following NPM/Node versions:
```
➜  sheltertech.org git:(365-upgrade-to-gatsby-4-nodejs-16) ✗ npm -v
8.19.4
➜  sheltertech.org git:(365-upgrade-to-gatsby-4-nodejs-16) ✗ node -v
v16.20.2
```

**Comment by richardxia** [comment]
Weird, that exactly matches what it should be according to this PR. In any case, let me merge this in for now and work on further package upgrades.

**Pull request merged**
