### PR TITLE
Update EIN acronym to all uppercase

### LINKED ISSUE #140: Update footer "ein" letters to uppercase
`EIN` is an acronym for **Employer Identification Number** and all the letters should be in uppercase.

### PR DESCRIPTION
**Pull request by candywang**
Fixed #140 by updating the `<Navigation>` and `<Layout>` components.

### CODE REVIEW

**Review by davidagustin — COMMENTED** [review]
I don't think we should touch the legacy files unless we really need to.

**Review by davidagustin — APPROVED** [review]
LGTM

**Comment by candywang** [comment]
Fixed #140 by updating the `<Layout>` component and the `<Footer>` stories file (for isolated visual reference).

**Review by ivanleeswe — APPROVED** [review]

**Review by richardxia — APPROVED** [review]
LGTM!

**Pull request merged**
