### PR TITLE
Update About Us Page

### LINKED ISSUE #266: Updates to About Us page
We got some feedback for the About Us page, and they're all pretty small fixes, so this should hopefully be a quick one:

1. In the ImageHeader component, remove the second (lower) image
2. Also in the ImageHeader component, feel free to remove all the extra CSS classes we had added to make the offsets and alignment match the original version of the component
3. In the Volunteer Spotlight component, use the newly cropped version of the photo of Laura found in https://www.figma.com/file/kKaWvJvyzhNS9hD21v7Ei5/ShelterTech.org-2020?node-id=1673%3A1764 (it's actually at the bottom of the Volunteer page in the Figma mocks, but we should use this photo for all instances of the Volunteer Spotlight of Laura on the site)

### PR DESCRIPTION
**Pull request by candywang**
I noticed the `articleSpotlightImage` image has a low resolution. Are we able to get a png with a higher resolution?

Closes #266.

### CODE REVIEW

**Review by richardxia — APPROVED** [review]
LGTM! Glad that we can get rid of the extra CSS styles.

Regarding your question:

> I noticed the articleSpotlightImage image has a low resolution. Are we able to get a png with a higher resolution?

@derekfidler, is there a higher resolution image that we have? But I don't think we need to block the merging of this PR on getting a higher resolution image, since the previous image was about the same quality level.

One last request: @candywang, could you use this newly cropped photo on the Volunteer page as well?

**Review by davidagustin — APPROVED** [review]
LGTM. I did this component in the beginning and I agree. We do need a higher resolution image.

**Comment by candywang** [comment]
I created an `images` folder in the `src/pages` directory for image files used across different pages. There is a duplicate file - `mission-hotel.jpeg` - in `src/pages/donate/mission-hotel.jpeg` and `src/pages/mission-hotel.jpeg`. Do we want to delete one and move the other to the `images` folder?

**Comment by richardxia** [comment]
> I created an `images` folder in the `src/pages` directory for image files used across different pages. There is a duplicate file - `mission-hotel.jpeg` - in `src/pages/donate/mission-hotel.jpeg` and `src/pages/mission-hotel.jpeg`. Do we want to delete one and move the other to the `images` folder?

Yes, I think that'd be great! These changes LGTM, so feel free to merge when you make that last change.

**Pull request merged**
